services:
  proxy:
    build:
      context: ../proxy
      dockerfile: Dockerfile
    container_name: dev-proxy
    volumes:
      - ./whitelist.conf:/etc/squid/whitelist.conf:ro
    networks:
      - default
      - proxy-net
    restart: unless-stopped

networks:
  proxy-net:
    name: proxy-net
    internal: true
